# generated by datamodel-codegen:
#   filename:  impact.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel, conint, constr


class ReviewOrderItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class MapRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    commit: constr(min_length=1)


class Comparison(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base: constr(min_length=1)
    head: constr(min_length=1)


class Status(Enum):
    added = 'added'
    modified = 'modified'
    deleted = 'deleted'
    renamed = 'renamed'
    copied = 'copied'
    type_changed = 'type_changed'


class FileChange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: constr(min_length=1)
    old_path: constr(min_length=1) | None = None
    status: Status
    node_id: constr(min_length=1) | None = None


class DirectDependent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    changed_node_id: constr(min_length=1)
    dependent_node_id: constr(min_length=1)


class Summary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    changed_files: conint(ge=0)
    mapped_files: conint(ge=0)
    direct_dependents: conint(ge=0)


class ImpactArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    map_ref: MapRef
    comparison: Comparison
    files: list[FileChange]
    direct_dependents: list[DirectDependent]
    review_order: list[ReviewOrderItem]
    summary: Summary
