# generated by datamodel-codegen:
#   filename:  map.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Repository(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    root: str
    commit: constr(min_length=1)
    generated_at: AwareDatetime


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    loc: conint(ge=0)
    fan_in: conint(ge=0)
    fan_out: conint(ge=0)


class Kind(Enum):
    component = 'component'
    module = 'module'
    file = 'file'


class ProseSource(Enum):
    heuristic = 'heuristic'
    llm = 'llm'


class Child(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class File(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    kind: Kind
    label: constr(min_length=1)
    summary: str
    prose_source: ProseSource
    children: list[Child]
    files: list[File]
    metrics: Metrics


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file: constr(min_length=1)
    line: conint(ge=1)


class Kind1(Enum):
    imports = 'imports'
    calls = 'calls'
    inherits = 'inherits'


class Edge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: constr(min_length=1)
    target: constr(min_length=1)
    kind: Kind1
    evidence: list[Evidence] = Field(..., min_length=1)
    label: str | None = None


class SystemItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class ComponentItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class ModuleItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Levels(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    system: list[SystemItem]
    component: dict[str, list[ComponentItem]]
    module: dict[str, list[ModuleItem]]


class MapArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    repo: Repository
    nodes: list[Node]
    edges: list[Edge]
    levels: Levels
