# generated by datamodel-codegen:
#   filename:  trace.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, confloat, conint, constr


class MapRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    commit: constr(min_length=1)


class Tool(Enum):
    Read = 'Read'
    Edit = 'Edit'
    Write = 'Write'
    Bash = 'Bash'
    Grep = 'Grep'
    Test = 'Test'


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    t: confloat(ge=0.0)
    tool: Tool
    path: str
    node_id: constr(min_length=1) | None
    detail: dict[str, str | int | float | bool | None]
    turn: conint(ge=0)


class Summary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    files_read: conint(ge=0)
    files_edited: conint(ge=0)
    tests_run: conint(ge=0)


class TraceArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    session_id: constr(min_length=1)
    agent: constr(min_length=1)
    map_ref: MapRef
    events: list[Event]
    summary: Summary
